"use client";

import { Navbar } from "flowbite-react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "./components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar
          fluid={true}
          rounded={true}
          className="bg-red-900 flex items-center justify-center text-2xl font-bold text-white"
        >
          Sibutran2
        </Navbar>
        {children}
        <Footer />
      </body>
    </html>
  );
}
