import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "./components/footer";
import { NavbarMain } from "./components/navbarMain";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="scroll-smooth transition duration-150 ease-in-out"
    >
      <body className={inter.className}>
        <NavbarMain />
        {children}
        <Footer />
      </body>
    </html>
  );
}
